services:
  postgres:
    image: postgres:16.6
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - social_networks

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - social_networks

  worker-instagram:
    build:
      context: ./workers/instagram
      dockerfile: Dockerfile
    container_name: worker_instagram
    restart: unless-stopped
    environment:
      - RMQ_URI=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - social_networks

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RMQ_URI=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - social_networks

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND__TCP_PORT}:${BACKEND__TCP_PORT}"
    environment:
      - DEBUG=False
      - TCP_PORT=${BACKEND__TCP_PORT}
      - STATE=${BACKEND__STATE}
      - SECRET_KEY=${BACKEND__SECRET_KEY}
      - AUTHENTICATION__ACCESS_TOKEN__SECRET_KEY=${BACKEND__AUTHENTICATION_ACCESS_TOKEN_SECRET_KEY}
      - DATABASE__URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - BROKER__URI=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - social_networks

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  social_networks:
    driver: bridge
