name: CiCd

on:
  push:
    paths:
      - 'backend/**'
      - 'bot/**'
      - 'workers/instagram/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'bot/**'
      - 'workers/instagram/**'

env:
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-backend
  BOT_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-bot
  INSTAGRAM_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-instagram-worker

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
      bot_changed: ${{ steps.filter.outputs.bot }}
      instagram_changed: ${{ steps.filter.outputs.instagram }}
    steps:
      - uses: actions/checkout@v3

      - name: Detect changed folders
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**'
            bot:
              - 'bot/**'
            instagram:
              - 'workers/instagram/**'

  backend-job:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run backend tests
        run: |
          cd backend
          make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t $BACKEND_IMAGE:latest ./backend
          docker push $BACKEND_IMAGE:latest

  bot-job:
    needs: detect-changes
    if: needs.detect-changes.outputs.bot_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run bot tests
        run: |
          cd bot
          make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push bot Docker image
        run: |
          docker build -t $BOT_IMAGE:latest ./bot
          docker push $BOT_IMAGE:latest

  instagram-job:
    needs: detect-changes
    if: needs.detect-changes.outputs.instagram_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Instagram worker tests
        run: |
          cd workers/instagram
          make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Instagram Docker image
        run: |
          docker build -t $INSTAGRAM_IMAGE:latest ./workers/instagram
          docker push $INSTAGRAM_IMAGE:latest
