# Generated by Django 5.1.6 on 2025-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="account",
            name="accounts_social__2f66b2_idx",
        ),
        migrations.RemoveField(
            model_name="account",
            name="social_media",
        ),
        migrations.AddField(
            model_name="account",
            name="provider",
            field=models.CharField(
                choices=[("INSTAGRAM", "Instagram")],
                default="INSTAGRAM",
                max_length=255,
                verbose_name="Provider social media",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["provider", "username"], name="accounts_provide_8eca86_idx"
            ),
        ),
    ]
