# Generated by Django 5.1.6 on 2025-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0003_alter_account_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="store_at",
        ),
    ]
