# Generated by Django 5.1.6 on 2025-03-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_media",
            "0005_tag_slug_alter_post_id_alter_tag_id_alter_tag_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
    ]
