# Generated by Django 5.1.6 on 2025-03-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="social_media.account",
            ),
        ),
    ]
