# Generated by Django 5.1.6 on 2025-03-17 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0007_alter_tracking_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tracking",
            options={
                "verbose_name": "Tracking account",
                "verbose_name_plural": "Tracking accounts",
            },
        ),
    ]
