# Generated by Django 5.1.6 on 2025-03-17 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0008_alter_tracking_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tracking",
            new_name="UserSubscription",
        ),
        migrations.AlterModelOptions(
            name="usersubscription",
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscription",
            },
        ),
        migrations.AlterModelTable(
            name="usersubscription",
            table="user_subscriptions",
        ),
    ]
