# Generated by Django 5.1.6 on 2025-03-17 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0009_rename_tracking_usersubscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
