# Generated by Django 5.1.6 on 2025-03-18 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0011_alter_usersubscription_account_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="account",
            new_name="social_medi_provide_112cf6_idx",
            old_name="accounts_provide_8eca86_idx",
        ),
        migrations.AlterModelTable(
            name="account",
            table=None,
        ),
        migrations.AlterModelTable(
            name="post",
            table=None,
        ),
        migrations.AlterModelTable(
            name="usersubscription",
            table=None,
        ),
    ]
