# Generated by Django 5.1.6 on 2025-03-18 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_media",
            "0012_rename_accounts_provide_8eca86_idx_social_medi_provide_112cf6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="social_media.account",
            ),
        ),
    ]
