# Generated by Django 5.1.6 on 2025-03-18 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0013_alter_usersubscription_account"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tag",
            table=None,
        ),
    ]
