# Generated by Django 5.1.6 on 2025-03-19 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0014_alter_tag_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["account", "user"], name="social_medi_account_61cf72_idx"
            ),
        ),
    ]
