# Generated by Django 5.1.6 on 2025-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0015_usersubscription_social_medi_account_61cf72_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="provider_uid",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Provider ID"
            ),
        ),
    ]
