# Generated by Django 5.1.6 on 2025-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0016_post_provider_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="provider_uid",
            new_name="uid",
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                fields=("account", "uid"), name="unique_account_provider_uid"
            ),
        ),
    ]
