# Generated by Django 5.1.7 on 2025-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0017_rename_provider_uid_post_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="follow_tags",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="social_media.tag"
            ),
        ),
    ]
